### ISSUE TITLE
TODO : workbook unit test 코드 작성

### ISSUE THREAD

**Issue by mokhs00** [MARS-crew/flip_be_nest#34]
- workbook
  - [x] 문제집 전체 조회
  - [x] 문제집 상세 조회
  - [x] 문제집 등록
  - [x] 문제집 수정
  - [x] 문제집 삭제
  - [x] 인기 문제집 전체 조회
  - [x] 내 문제집 전체 조회
